stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: omerdevsecops/devsecops-omerops
  IMAGE_TAG: harness-app-1.0

run_tests:
  stage: test
  image: python:3.9-alpine
  script:
    - echo "No tests in this app to run"

build_image:
  stage: build
  image: docker:28.3.3-cli
  services:
    - docker:28.3.3-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  script:
    - docker build -t "$IMAGE_NAME:$IMAGE_TAG" .
    - docker push "$IMAGE_NAME:$IMAGE_TAG"

deploy:
  stage: deploy
  image: alpine:3.20
  script:
    - apk add --no-cache openssh-client
    - chmod 400 "$SSH_KEY"
    - >
      ssh -o StrictHostKeyChecking=no -i "$SSH_KEY"
      "${EC2_USER:-ubuntu}@${EC2_HOST:-ec2-13-223-73-110.compute-1.amazonaws.com}"
      "echo '✅ Connected to EC2'; \
       uname -a; \
       docker login -u $REGISTRY_USER -p $REGISTRY_PASS; \
       docker stop harness-demo || true; \
       docker rm harness-demo || true; \
       docker run -d --name harness-demo -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG"
