# 🟡 Single-Stage Dockerfile: Build + Run in One

FROM golang:1.24-alpine

RUN apk add --no-cache git curl

WORKDIR /app

COPY ./caddy /app

WORKDIR /app/cmd/caddy

RUN go build -o /usr/bin/caddy

COPY ./Caddyfile /etc/caddy/Caddyfile

EXPOSE 80 443

ENTRYPOINT ["caddy"]
CMD ["run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]

